[workspace]
authors = ["nmarticorena <nicolas.marticorena.vidal@gmail.com>"]
channels = ["conda-forge"]
name = "motion_tools"
platforms = ["linux-64"]
version = "0.1.3"

[environments]
dev = "dev"

[tasks]

[dependencies]
rerun-sdk = ">=0.29.1,<0.30"
numpy = ">=2.4.2,<3"
python = ">=3.14.3,<3.15"
tyro = ">=1.0.6,<2"
hatchling = ">=1.28.0,<2"

[pypi-dependencies]
motion-tools = { path = "./" , editable = true}

[feature.dev.dependencies]
pre-commit = "*"
ruff = ">=0.15.0,<0.16"

[feature.dev.tasks]
clean = "ruff format"
