[workspace]
authors = ["nmarticorena <nicolas.marticorena.vidal@gmail.com>"]
channels = ["conda-forge"]
name = "motions_tools"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rerun-sdk = ">=0.29.1,<0.30"
numpy = ">=2.4.2,<3"
python = ">=3.14.3,<3.15"
